# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ../LotteryPage/LotteryPage/GeneratedFiles/ui_LotteryPage.h \
    ../LotteryPage/LotteryPage/LotteryPage.h
SOURCES += ../LotteryPage/LotteryPage/LotteryPage.cpp \
    ../LotteryPage/LotteryPage/main.cpp
FORMS += ../LotteryPage/LotteryPage/LotteryPage.ui
RESOURCES += LotteryPage.qrc
