/********************************************************************************
** Form generated from reading UI file 'LotteryPage.ui'
**
** Created by: Qt User Interface Compiler version 5.11.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LOTTERYPAGE_H
#define UI_LOTTERYPAGE_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_LotteryPageClass
{
public:
    QWidget *centralWidget;
    QPushButton *ThirdPrize;
    QPushButton *SecondPrize;
    QPushButton *FirstPrize;
    QStackedWidget *m_pStackWidget;
    QWidget *FirstPrizePage;
    QLineEdit *lineEdit;
    QWidget *SecondPrizePage;
    QLineEdit *SecondPrizelineEdit_0;
    QLineEdit *SecondPrizelineEdit_1;
    QLineEdit *SecondPrizelineEdit_2;
    QLineEdit *SecondPrizelineEdit_3;
    QLineEdit *SecondPrizelineEdit_4;
    QLineEdit *SecondPrizelineEdit_5;
    QPushButton *SecondPrizeBtn_0;
    QPushButton *SecondPrizeBtn_1;
    QPushButton *SecondPrizeBtn_2;
    QPushButton *SecondPrizeBtn_3;
    QPushButton *SecondPrizeBtn_4;
    QPushButton *SecondPrizeBtn_5;
    QWidget *ThirdPrizePage;
    QLineEdit *RdPrzLE_0;
    QLineEdit *RdPrzLE_1;
    QLineEdit *RdPrzLE_2;
    QLineEdit *RdPrzLE_3;
    QLineEdit *RdPrzLE_4;
    QLineEdit *RdPrzLE_5;
    QLineEdit *RdPrzLE_10;
    QLineEdit *RdPrzLE_6;
    QLineEdit *RdPrzLE_7;
    QLineEdit *RdPrzLE_8;
    QLineEdit *RdPrzLE_11;
    QLineEdit *RdPrzLE_12;
    QLineEdit *RdPrzLE_13;
    QLineEdit *RdPrzLE_14;
    QLineEdit *RdPrzLE_9;
    QWidget *LuckyPrizePage;
    QLineEdit *LkPrzLE_0;
    QLineEdit *LkPrzLE_1;
    QLineEdit *LkPrzLE_2;
    QLineEdit *LkPrzLE_3;
    QLineEdit *LkPrzLE_5;
    QLineEdit *LkPrzLE_10;
    QLineEdit *LkPrzLE_15;
    QLineEdit *LkPrzLE_4;
    QLineEdit *LkPrzLE_6;
    QLineEdit *LkPrzLE_7;
    QLineEdit *LkPrzLE_8;
    QLineEdit *LkPrzLE_9;
    QLineEdit *LkPrzLE_11;
    QLineEdit *LkPrzLE_12;
    QLineEdit *LkPrzLE_13;
    QLineEdit *LkPrzLE_14;
    QLineEdit *LkPrzLE_16;
    QLineEdit *LkPrzLE_17;
    QLineEdit *LkPrzLE_18;
    QLineEdit *LkPrzLE_19;
    QWidget *ThirdPrizePage2;
    QLineEdit *RdPrzLE2_14;
    QLineEdit *RdPrzLE2_13;
    QLineEdit *RdPrzLE2_12;
    QLineEdit *RdPrzLE2_11;
    QLineEdit *RdPrzLE2_10;
    QLineEdit *RdPrzLE2_5;
    QLineEdit *RdPrzLE2_6;
    QLineEdit *RdPrzLE2_7;
    QLineEdit *RdPrzLE2_8;
    QLineEdit *RdPrzLE2_9;
    QLineEdit *RdPrzLE2_0;
    QLineEdit *RdPrzLE2_1;
    QLineEdit *RdPrzLE2_2;
    QLineEdit *RdPrzLE2_3;
    QLineEdit *RdPrzLE2_4;
    QWidget *LkPrz2;
    QLineEdit *LkPrzLE2_19;
    QLineEdit *LkPrzLE2_18;
    QLineEdit *LkPrzLE2_17;
    QLineEdit *LkPrzLE2_16;
    QLineEdit *LkPrzLE2_15;
    QLineEdit *LkPrzLE2_10;
    QLineEdit *LkPrzLE2_11;
    QLineEdit *LkPrzLE2_12;
    QLineEdit *LkPrzLE2_13;
    QLineEdit *LkPrzLE2_14;
    QLineEdit *LkPrzLE2_5;
    QLineEdit *LkPrzLE2_6;
    QLineEdit *LkPrzLE2_7;
    QLineEdit *LkPrzLE2_8;
    QLineEdit *LkPrzLE2_9;
    QLineEdit *LkPrzLE2_0;
    QLineEdit *LkPrzLE2_1;
    QLineEdit *LkPrzLE2_2;
    QLineEdit *LkPrzLE2_3;
    QLineEdit *LkPrzLE2_4;
    QWidget *LkPrz3;
    QLineEdit *LkPrzLE3_19;
    QLineEdit *LkPrzLE3_18;
    QLineEdit *LkPrzLE3_17;
    QLineEdit *LkPrzLE3_16;
    QLineEdit *LkPrzLE3_15;
    QLineEdit *LkPrzLE3_14;
    QLineEdit *LkPrzLE3_13;
    QLineEdit *LkPrzLE3_12;
    QLineEdit *LkPrzLE3_11;
    QLineEdit *LkPrzLE3_10;
    QLineEdit *LkPrzLE3_5;
    QLineEdit *LkPrzLE3_6;
    QLineEdit *LkPrzLE3_7;
    QLineEdit *LkPrzLE3_8;
    QLineEdit *LkPrzLE3_9;
    QLineEdit *LkPrzLE3_0;
    QLineEdit *LkPrzLE3_1;
    QLineEdit *LkPrzLE3_2;
    QLineEdit *LkPrzLE3_3;
    QLineEdit *LkPrzLE3_4;
    QPushButton *LuckyPrize;
    QPushButton *Start;
    QPushButton *Pause;
    QPushButton *ThirdPrize_2;
    QPushButton *LuckyPrize_2;
    QPushButton *LuckyPrize_3;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *LotteryPageClass)
    {
        if (LotteryPageClass->objectName().isEmpty())
            LotteryPageClass->setObjectName(QStringLiteral("LotteryPageClass"));
        LotteryPageClass->resize(1181, 719);
        centralWidget = new QWidget(LotteryPageClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        ThirdPrize = new QPushButton(centralWidget);
        ThirdPrize->setObjectName(QStringLiteral("ThirdPrize"));
        ThirdPrize->setGeometry(QRect(10, 160, 221, 51));
        QFont font;
        font.setFamily(QStringLiteral("Adobe Arabic"));
        font.setPointSize(24);
        ThirdPrize->setFont(font);
        SecondPrize = new QPushButton(centralWidget);
        SecondPrize->setObjectName(QStringLiteral("SecondPrize"));
        SecondPrize->setGeometry(QRect(10, 90, 221, 51));
        SecondPrize->setFont(font);
        FirstPrize = new QPushButton(centralWidget);
        FirstPrize->setObjectName(QStringLiteral("FirstPrize"));
        FirstPrize->setGeometry(QRect(10, 20, 221, 51));
        FirstPrize->setFont(font);
        m_pStackWidget = new QStackedWidget(centralWidget);
        m_pStackWidget->setObjectName(QStringLiteral("m_pStackWidget"));
        m_pStackWidget->setGeometry(QRect(240, 10, 931, 621));
        FirstPrizePage = new QWidget();
        FirstPrizePage->setObjectName(QStringLiteral("FirstPrizePage"));
        lineEdit = new QLineEdit(FirstPrizePage);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(150, 150, 671, 301));
        QFont font1;
        font1.setFamily(QStringLiteral("Adobe Arabic"));
        font1.setPointSize(72);
        font1.setBold(false);
        font1.setWeight(50);
        lineEdit->setFont(font1);
        lineEdit->setAlignment(Qt::AlignCenter);
        m_pStackWidget->addWidget(FirstPrizePage);
        SecondPrizePage = new QWidget();
        SecondPrizePage->setObjectName(QStringLiteral("SecondPrizePage"));
        SecondPrizelineEdit_0 = new QLineEdit(SecondPrizePage);
        SecondPrizelineEdit_0->setObjectName(QStringLiteral("SecondPrizelineEdit_0"));
        SecondPrizelineEdit_0->setGeometry(QRect(40, 40, 231, 161));
        QFont font2;
        font2.setFamily(QStringLiteral("Adobe Arabic"));
        font2.setPointSize(48);
        font2.setBold(true);
        font2.setWeight(75);
        SecondPrizelineEdit_0->setFont(font2);
        SecondPrizelineEdit_0->setAlignment(Qt::AlignCenter);
        SecondPrizelineEdit_1 = new QLineEdit(SecondPrizePage);
        SecondPrizelineEdit_1->setObjectName(QStringLiteral("SecondPrizelineEdit_1"));
        SecondPrizelineEdit_1->setGeometry(QRect(330, 40, 231, 161));
        SecondPrizelineEdit_1->setFont(font2);
        SecondPrizelineEdit_1->setAlignment(Qt::AlignCenter);
        SecondPrizelineEdit_2 = new QLineEdit(SecondPrizePage);
        SecondPrizelineEdit_2->setObjectName(QStringLiteral("SecondPrizelineEdit_2"));
        SecondPrizelineEdit_2->setGeometry(QRect(620, 40, 231, 161));
        SecondPrizelineEdit_2->setFont(font2);
        SecondPrizelineEdit_2->setAlignment(Qt::AlignCenter);
        SecondPrizelineEdit_3 = new QLineEdit(SecondPrizePage);
        SecondPrizelineEdit_3->setObjectName(QStringLiteral("SecondPrizelineEdit_3"));
        SecondPrizelineEdit_3->setGeometry(QRect(40, 330, 231, 161));
        SecondPrizelineEdit_3->setFont(font2);
        SecondPrizelineEdit_3->setAlignment(Qt::AlignCenter);
        SecondPrizelineEdit_4 = new QLineEdit(SecondPrizePage);
        SecondPrizelineEdit_4->setObjectName(QStringLiteral("SecondPrizelineEdit_4"));
        SecondPrizelineEdit_4->setGeometry(QRect(330, 330, 231, 161));
        SecondPrizelineEdit_4->setFont(font2);
        SecondPrizelineEdit_4->setAlignment(Qt::AlignCenter);
        SecondPrizelineEdit_5 = new QLineEdit(SecondPrizePage);
        SecondPrizelineEdit_5->setObjectName(QStringLiteral("SecondPrizelineEdit_5"));
        SecondPrizelineEdit_5->setGeometry(QRect(620, 330, 231, 161));
        SecondPrizelineEdit_5->setFont(font2);
        SecondPrizelineEdit_5->setAlignment(Qt::AlignCenter);
        SecondPrizeBtn_0 = new QPushButton(SecondPrizePage);
        SecondPrizeBtn_0->setObjectName(QStringLiteral("SecondPrizeBtn_0"));
        SecondPrizeBtn_0->setGeometry(QRect(60, 220, 191, 51));
        SecondPrizeBtn_1 = new QPushButton(SecondPrizePage);
        SecondPrizeBtn_1->setObjectName(QStringLiteral("SecondPrizeBtn_1"));
        SecondPrizeBtn_1->setGeometry(QRect(350, 220, 191, 51));
        SecondPrizeBtn_2 = new QPushButton(SecondPrizePage);
        SecondPrizeBtn_2->setObjectName(QStringLiteral("SecondPrizeBtn_2"));
        SecondPrizeBtn_2->setGeometry(QRect(640, 220, 191, 51));
        SecondPrizeBtn_3 = new QPushButton(SecondPrizePage);
        SecondPrizeBtn_3->setObjectName(QStringLiteral("SecondPrizeBtn_3"));
        SecondPrizeBtn_3->setGeometry(QRect(60, 510, 191, 51));
        SecondPrizeBtn_4 = new QPushButton(SecondPrizePage);
        SecondPrizeBtn_4->setObjectName(QStringLiteral("SecondPrizeBtn_4"));
        SecondPrizeBtn_4->setGeometry(QRect(350, 510, 191, 51));
        SecondPrizeBtn_5 = new QPushButton(SecondPrizePage);
        SecondPrizeBtn_5->setObjectName(QStringLiteral("SecondPrizeBtn_5"));
        SecondPrizeBtn_5->setGeometry(QRect(640, 510, 191, 51));
        m_pStackWidget->addWidget(SecondPrizePage);
        ThirdPrizePage = new QWidget();
        ThirdPrizePage->setObjectName(QStringLiteral("ThirdPrizePage"));
        RdPrzLE_0 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_0->setObjectName(QStringLiteral("RdPrzLE_0"));
        RdPrzLE_0->setGeometry(QRect(40, 40, 141, 121));
        QFont font3;
        font3.setFamily(QStringLiteral("Adobe Arabic"));
        font3.setPointSize(36);
        font3.setBold(false);
        font3.setWeight(50);
        RdPrzLE_0->setFont(font3);
        RdPrzLE_0->setAlignment(Qt::AlignCenter);
        RdPrzLE_1 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_1->setObjectName(QStringLiteral("RdPrzLE_1"));
        RdPrzLE_1->setGeometry(QRect(220, 40, 141, 121));
        RdPrzLE_1->setFont(font3);
        RdPrzLE_1->setAlignment(Qt::AlignCenter);
        RdPrzLE_2 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_2->setObjectName(QStringLiteral("RdPrzLE_2"));
        RdPrzLE_2->setGeometry(QRect(400, 40, 141, 121));
        RdPrzLE_2->setFont(font3);
        RdPrzLE_2->setAlignment(Qt::AlignCenter);
        RdPrzLE_3 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_3->setObjectName(QStringLiteral("RdPrzLE_3"));
        RdPrzLE_3->setGeometry(QRect(580, 40, 141, 121));
        RdPrzLE_3->setFont(font3);
        RdPrzLE_3->setAlignment(Qt::AlignCenter);
        RdPrzLE_4 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_4->setObjectName(QStringLiteral("RdPrzLE_4"));
        RdPrzLE_4->setGeometry(QRect(760, 40, 141, 121));
        RdPrzLE_4->setFont(font3);
        RdPrzLE_4->setAlignment(Qt::AlignCenter);
        RdPrzLE_5 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_5->setObjectName(QStringLiteral("RdPrzLE_5"));
        RdPrzLE_5->setGeometry(QRect(40, 240, 141, 121));
        RdPrzLE_5->setFont(font3);
        RdPrzLE_5->setAlignment(Qt::AlignCenter);
        RdPrzLE_10 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_10->setObjectName(QStringLiteral("RdPrzLE_10"));
        RdPrzLE_10->setGeometry(QRect(40, 440, 141, 121));
        RdPrzLE_10->setFont(font3);
        RdPrzLE_10->setAlignment(Qt::AlignCenter);
        RdPrzLE_6 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_6->setObjectName(QStringLiteral("RdPrzLE_6"));
        RdPrzLE_6->setGeometry(QRect(220, 240, 141, 121));
        RdPrzLE_6->setFont(font3);
        RdPrzLE_6->setAlignment(Qt::AlignCenter);
        RdPrzLE_7 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_7->setObjectName(QStringLiteral("RdPrzLE_7"));
        RdPrzLE_7->setGeometry(QRect(400, 240, 141, 121));
        RdPrzLE_7->setFont(font3);
        RdPrzLE_7->setAlignment(Qt::AlignCenter);
        RdPrzLE_8 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_8->setObjectName(QStringLiteral("RdPrzLE_8"));
        RdPrzLE_8->setGeometry(QRect(580, 240, 141, 121));
        RdPrzLE_8->setFont(font3);
        RdPrzLE_8->setAlignment(Qt::AlignCenter);
        RdPrzLE_11 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_11->setObjectName(QStringLiteral("RdPrzLE_11"));
        RdPrzLE_11->setGeometry(QRect(220, 440, 141, 121));
        RdPrzLE_11->setFont(font3);
        RdPrzLE_11->setAlignment(Qt::AlignCenter);
        RdPrzLE_12 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_12->setObjectName(QStringLiteral("RdPrzLE_12"));
        RdPrzLE_12->setGeometry(QRect(400, 440, 141, 121));
        RdPrzLE_12->setFont(font3);
        RdPrzLE_12->setAlignment(Qt::AlignCenter);
        RdPrzLE_13 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_13->setObjectName(QStringLiteral("RdPrzLE_13"));
        RdPrzLE_13->setGeometry(QRect(580, 440, 141, 121));
        RdPrzLE_13->setFont(font3);
        RdPrzLE_13->setAlignment(Qt::AlignCenter);
        RdPrzLE_14 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_14->setObjectName(QStringLiteral("RdPrzLE_14"));
        RdPrzLE_14->setGeometry(QRect(760, 440, 141, 121));
        RdPrzLE_14->setFont(font3);
        RdPrzLE_14->setAlignment(Qt::AlignCenter);
        RdPrzLE_9 = new QLineEdit(ThirdPrizePage);
        RdPrzLE_9->setObjectName(QStringLiteral("RdPrzLE_9"));
        RdPrzLE_9->setGeometry(QRect(760, 240, 141, 121));
        RdPrzLE_9->setFont(font3);
        RdPrzLE_9->setAlignment(Qt::AlignCenter);
        m_pStackWidget->addWidget(ThirdPrizePage);
        LuckyPrizePage = new QWidget();
        LuckyPrizePage->setObjectName(QStringLiteral("LuckyPrizePage"));
        LkPrzLE_0 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_0->setObjectName(QStringLiteral("LkPrzLE_0"));
        LkPrzLE_0->setGeometry(QRect(40, 30, 151, 101));
        QFont font4;
        font4.setFamily(QStringLiteral("Adobe Caslon Pro"));
        font4.setPointSize(24);
        LkPrzLE_0->setFont(font4);
        LkPrzLE_0->setAlignment(Qt::AlignCenter);
        LkPrzLE_1 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_1->setObjectName(QStringLiteral("LkPrzLE_1"));
        LkPrzLE_1->setGeometry(QRect(220, 30, 151, 101));
        LkPrzLE_1->setFont(font4);
        LkPrzLE_1->setAlignment(Qt::AlignCenter);
        LkPrzLE_2 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_2->setObjectName(QStringLiteral("LkPrzLE_2"));
        LkPrzLE_2->setGeometry(QRect(400, 30, 151, 101));
        LkPrzLE_2->setFont(font4);
        LkPrzLE_2->setAlignment(Qt::AlignCenter);
        LkPrzLE_3 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_3->setObjectName(QStringLiteral("LkPrzLE_3"));
        LkPrzLE_3->setGeometry(QRect(580, 30, 151, 101));
        LkPrzLE_3->setFont(font4);
        LkPrzLE_3->setAlignment(Qt::AlignCenter);
        LkPrzLE_5 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_5->setObjectName(QStringLiteral("LkPrzLE_5"));
        LkPrzLE_5->setGeometry(QRect(40, 170, 151, 101));
        LkPrzLE_5->setFont(font4);
        LkPrzLE_5->setAlignment(Qt::AlignCenter);
        LkPrzLE_10 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_10->setObjectName(QStringLiteral("LkPrzLE_10"));
        LkPrzLE_10->setGeometry(QRect(40, 310, 151, 101));
        LkPrzLE_10->setFont(font4);
        LkPrzLE_10->setAlignment(Qt::AlignCenter);
        LkPrzLE_15 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_15->setObjectName(QStringLiteral("LkPrzLE_15"));
        LkPrzLE_15->setGeometry(QRect(40, 450, 151, 101));
        LkPrzLE_15->setFont(font4);
        LkPrzLE_15->setAlignment(Qt::AlignCenter);
        LkPrzLE_4 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_4->setObjectName(QStringLiteral("LkPrzLE_4"));
        LkPrzLE_4->setGeometry(QRect(760, 30, 151, 101));
        LkPrzLE_4->setFont(font4);
        LkPrzLE_4->setAlignment(Qt::AlignCenter);
        LkPrzLE_6 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_6->setObjectName(QStringLiteral("LkPrzLE_6"));
        LkPrzLE_6->setGeometry(QRect(220, 170, 151, 101));
        LkPrzLE_6->setFont(font4);
        LkPrzLE_6->setAlignment(Qt::AlignCenter);
        LkPrzLE_7 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_7->setObjectName(QStringLiteral("LkPrzLE_7"));
        LkPrzLE_7->setGeometry(QRect(400, 170, 151, 101));
        LkPrzLE_7->setFont(font4);
        LkPrzLE_7->setAlignment(Qt::AlignCenter);
        LkPrzLE_8 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_8->setObjectName(QStringLiteral("LkPrzLE_8"));
        LkPrzLE_8->setGeometry(QRect(580, 170, 151, 101));
        LkPrzLE_8->setFont(font4);
        LkPrzLE_8->setAlignment(Qt::AlignCenter);
        LkPrzLE_9 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_9->setObjectName(QStringLiteral("LkPrzLE_9"));
        LkPrzLE_9->setGeometry(QRect(760, 170, 151, 101));
        LkPrzLE_9->setFont(font4);
        LkPrzLE_9->setAlignment(Qt::AlignCenter);
        LkPrzLE_11 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_11->setObjectName(QStringLiteral("LkPrzLE_11"));
        LkPrzLE_11->setGeometry(QRect(220, 310, 151, 101));
        LkPrzLE_11->setFont(font4);
        LkPrzLE_11->setAlignment(Qt::AlignCenter);
        LkPrzLE_12 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_12->setObjectName(QStringLiteral("LkPrzLE_12"));
        LkPrzLE_12->setGeometry(QRect(400, 310, 151, 101));
        LkPrzLE_12->setFont(font4);
        LkPrzLE_12->setAlignment(Qt::AlignCenter);
        LkPrzLE_13 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_13->setObjectName(QStringLiteral("LkPrzLE_13"));
        LkPrzLE_13->setGeometry(QRect(580, 310, 151, 101));
        LkPrzLE_13->setFont(font4);
        LkPrzLE_13->setAlignment(Qt::AlignCenter);
        LkPrzLE_14 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_14->setObjectName(QStringLiteral("LkPrzLE_14"));
        LkPrzLE_14->setGeometry(QRect(760, 310, 151, 101));
        LkPrzLE_14->setFont(font4);
        LkPrzLE_14->setAlignment(Qt::AlignCenter);
        LkPrzLE_16 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_16->setObjectName(QStringLiteral("LkPrzLE_16"));
        LkPrzLE_16->setGeometry(QRect(220, 450, 151, 101));
        LkPrzLE_16->setFont(font4);
        LkPrzLE_16->setAlignment(Qt::AlignCenter);
        LkPrzLE_17 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_17->setObjectName(QStringLiteral("LkPrzLE_17"));
        LkPrzLE_17->setGeometry(QRect(400, 450, 151, 101));
        LkPrzLE_17->setFont(font4);
        LkPrzLE_17->setAlignment(Qt::AlignCenter);
        LkPrzLE_18 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_18->setObjectName(QStringLiteral("LkPrzLE_18"));
        LkPrzLE_18->setGeometry(QRect(580, 450, 151, 101));
        LkPrzLE_18->setFont(font4);
        LkPrzLE_18->setAlignment(Qt::AlignCenter);
        LkPrzLE_19 = new QLineEdit(LuckyPrizePage);
        LkPrzLE_19->setObjectName(QStringLiteral("LkPrzLE_19"));
        LkPrzLE_19->setGeometry(QRect(760, 450, 151, 101));
        QFont font5;
        font5.setFamily(QStringLiteral("Adobe Caslon Pro"));
        font5.setPointSize(20);
        LkPrzLE_19->setFont(font5);
        LkPrzLE_19->setAlignment(Qt::AlignCenter);
        m_pStackWidget->addWidget(LuckyPrizePage);
        ThirdPrizePage2 = new QWidget();
        ThirdPrizePage2->setObjectName(QStringLiteral("ThirdPrizePage2"));
        RdPrzLE2_14 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_14->setObjectName(QStringLiteral("RdPrzLE2_14"));
        RdPrzLE2_14->setGeometry(QRect(760, 440, 141, 121));
        RdPrzLE2_14->setFont(font3);
        RdPrzLE2_14->setAlignment(Qt::AlignCenter);
        RdPrzLE2_13 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_13->setObjectName(QStringLiteral("RdPrzLE2_13"));
        RdPrzLE2_13->setGeometry(QRect(580, 440, 141, 121));
        RdPrzLE2_13->setFont(font3);
        RdPrzLE2_13->setAlignment(Qt::AlignCenter);
        RdPrzLE2_12 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_12->setObjectName(QStringLiteral("RdPrzLE2_12"));
        RdPrzLE2_12->setGeometry(QRect(400, 440, 141, 121));
        RdPrzLE2_12->setFont(font3);
        RdPrzLE2_12->setAlignment(Qt::AlignCenter);
        RdPrzLE2_11 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_11->setObjectName(QStringLiteral("RdPrzLE2_11"));
        RdPrzLE2_11->setGeometry(QRect(220, 440, 141, 121));
        RdPrzLE2_11->setFont(font3);
        RdPrzLE2_11->setAlignment(Qt::AlignCenter);
        RdPrzLE2_10 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_10->setObjectName(QStringLiteral("RdPrzLE2_10"));
        RdPrzLE2_10->setGeometry(QRect(40, 440, 141, 121));
        RdPrzLE2_10->setFont(font3);
        RdPrzLE2_10->setAlignment(Qt::AlignCenter);
        RdPrzLE2_5 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_5->setObjectName(QStringLiteral("RdPrzLE2_5"));
        RdPrzLE2_5->setGeometry(QRect(40, 240, 141, 121));
        RdPrzLE2_5->setFont(font3);
        RdPrzLE2_5->setAlignment(Qt::AlignCenter);
        RdPrzLE2_6 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_6->setObjectName(QStringLiteral("RdPrzLE2_6"));
        RdPrzLE2_6->setGeometry(QRect(220, 240, 141, 121));
        RdPrzLE2_6->setFont(font3);
        RdPrzLE2_6->setAlignment(Qt::AlignCenter);
        RdPrzLE2_7 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_7->setObjectName(QStringLiteral("RdPrzLE2_7"));
        RdPrzLE2_7->setGeometry(QRect(400, 240, 141, 121));
        RdPrzLE2_7->setFont(font3);
        RdPrzLE2_7->setAlignment(Qt::AlignCenter);
        RdPrzLE2_8 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_8->setObjectName(QStringLiteral("RdPrzLE2_8"));
        RdPrzLE2_8->setGeometry(QRect(580, 240, 141, 121));
        RdPrzLE2_8->setFont(font3);
        RdPrzLE2_8->setAlignment(Qt::AlignCenter);
        RdPrzLE2_9 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_9->setObjectName(QStringLiteral("RdPrzLE2_9"));
        RdPrzLE2_9->setGeometry(QRect(760, 240, 141, 121));
        RdPrzLE2_9->setFont(font3);
        RdPrzLE2_9->setAlignment(Qt::AlignCenter);
        RdPrzLE2_0 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_0->setObjectName(QStringLiteral("RdPrzLE2_0"));
        RdPrzLE2_0->setGeometry(QRect(40, 40, 141, 121));
        RdPrzLE2_0->setFont(font3);
        RdPrzLE2_0->setAlignment(Qt::AlignCenter);
        RdPrzLE2_1 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_1->setObjectName(QStringLiteral("RdPrzLE2_1"));
        RdPrzLE2_1->setGeometry(QRect(220, 40, 141, 121));
        RdPrzLE2_1->setFont(font3);
        RdPrzLE2_1->setAlignment(Qt::AlignCenter);
        RdPrzLE2_2 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_2->setObjectName(QStringLiteral("RdPrzLE2_2"));
        RdPrzLE2_2->setGeometry(QRect(400, 40, 141, 121));
        RdPrzLE2_2->setFont(font3);
        RdPrzLE2_2->setAlignment(Qt::AlignCenter);
        RdPrzLE2_3 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_3->setObjectName(QStringLiteral("RdPrzLE2_3"));
        RdPrzLE2_3->setGeometry(QRect(580, 40, 141, 121));
        RdPrzLE2_3->setFont(font3);
        RdPrzLE2_3->setAlignment(Qt::AlignCenter);
        RdPrzLE2_4 = new QLineEdit(ThirdPrizePage2);
        RdPrzLE2_4->setObjectName(QStringLiteral("RdPrzLE2_4"));
        RdPrzLE2_4->setGeometry(QRect(760, 40, 141, 121));
        RdPrzLE2_4->setFont(font3);
        RdPrzLE2_4->setAlignment(Qt::AlignCenter);
        m_pStackWidget->addWidget(ThirdPrizePage2);
        LkPrz2 = new QWidget();
        LkPrz2->setObjectName(QStringLiteral("LkPrz2"));
        LkPrzLE2_19 = new QLineEdit(LkPrz2);
        LkPrzLE2_19->setObjectName(QStringLiteral("LkPrzLE2_19"));
        LkPrzLE2_19->setGeometry(QRect(760, 450, 151, 101));
        LkPrzLE2_19->setFont(font4);
        LkPrzLE2_19->setAlignment(Qt::AlignCenter);
        LkPrzLE2_18 = new QLineEdit(LkPrz2);
        LkPrzLE2_18->setObjectName(QStringLiteral("LkPrzLE2_18"));
        LkPrzLE2_18->setGeometry(QRect(580, 450, 151, 101));
        LkPrzLE2_18->setFont(font4);
        LkPrzLE2_18->setAlignment(Qt::AlignCenter);
        LkPrzLE2_17 = new QLineEdit(LkPrz2);
        LkPrzLE2_17->setObjectName(QStringLiteral("LkPrzLE2_17"));
        LkPrzLE2_17->setGeometry(QRect(400, 450, 151, 101));
        LkPrzLE2_17->setFont(font4);
        LkPrzLE2_17->setAlignment(Qt::AlignCenter);
        LkPrzLE2_16 = new QLineEdit(LkPrz2);
        LkPrzLE2_16->setObjectName(QStringLiteral("LkPrzLE2_16"));
        LkPrzLE2_16->setGeometry(QRect(220, 450, 151, 101));
        LkPrzLE2_16->setFont(font4);
        LkPrzLE2_16->setAlignment(Qt::AlignCenter);
        LkPrzLE2_15 = new QLineEdit(LkPrz2);
        LkPrzLE2_15->setObjectName(QStringLiteral("LkPrzLE2_15"));
        LkPrzLE2_15->setGeometry(QRect(40, 450, 151, 101));
        LkPrzLE2_15->setFont(font4);
        LkPrzLE2_15->setAlignment(Qt::AlignCenter);
        LkPrzLE2_10 = new QLineEdit(LkPrz2);
        LkPrzLE2_10->setObjectName(QStringLiteral("LkPrzLE2_10"));
        LkPrzLE2_10->setGeometry(QRect(40, 310, 151, 101));
        LkPrzLE2_10->setFont(font4);
        LkPrzLE2_10->setAlignment(Qt::AlignCenter);
        LkPrzLE2_11 = new QLineEdit(LkPrz2);
        LkPrzLE2_11->setObjectName(QStringLiteral("LkPrzLE2_11"));
        LkPrzLE2_11->setGeometry(QRect(220, 310, 151, 101));
        LkPrzLE2_11->setFont(font4);
        LkPrzLE2_11->setAlignment(Qt::AlignCenter);
        LkPrzLE2_12 = new QLineEdit(LkPrz2);
        LkPrzLE2_12->setObjectName(QStringLiteral("LkPrzLE2_12"));
        LkPrzLE2_12->setGeometry(QRect(400, 310, 151, 101));
        LkPrzLE2_12->setFont(font4);
        LkPrzLE2_12->setAlignment(Qt::AlignCenter);
        LkPrzLE2_13 = new QLineEdit(LkPrz2);
        LkPrzLE2_13->setObjectName(QStringLiteral("LkPrzLE2_13"));
        LkPrzLE2_13->setGeometry(QRect(580, 310, 151, 101));
        LkPrzLE2_13->setFont(font4);
        LkPrzLE2_13->setAlignment(Qt::AlignCenter);
        LkPrzLE2_14 = new QLineEdit(LkPrz2);
        LkPrzLE2_14->setObjectName(QStringLiteral("LkPrzLE2_14"));
        LkPrzLE2_14->setGeometry(QRect(760, 310, 151, 101));
        LkPrzLE2_14->setFont(font4);
        LkPrzLE2_14->setAlignment(Qt::AlignCenter);
        LkPrzLE2_5 = new QLineEdit(LkPrz2);
        LkPrzLE2_5->setObjectName(QStringLiteral("LkPrzLE2_5"));
        LkPrzLE2_5->setGeometry(QRect(40, 170, 151, 101));
        LkPrzLE2_5->setFont(font4);
        LkPrzLE2_5->setAlignment(Qt::AlignCenter);
        LkPrzLE2_6 = new QLineEdit(LkPrz2);
        LkPrzLE2_6->setObjectName(QStringLiteral("LkPrzLE2_6"));
        LkPrzLE2_6->setGeometry(QRect(220, 170, 151, 101));
        LkPrzLE2_6->setFont(font4);
        LkPrzLE2_6->setAlignment(Qt::AlignCenter);
        LkPrzLE2_7 = new QLineEdit(LkPrz2);
        LkPrzLE2_7->setObjectName(QStringLiteral("LkPrzLE2_7"));
        LkPrzLE2_7->setGeometry(QRect(400, 170, 151, 101));
        LkPrzLE2_7->setFont(font4);
        LkPrzLE2_7->setAlignment(Qt::AlignCenter);
        LkPrzLE2_8 = new QLineEdit(LkPrz2);
        LkPrzLE2_8->setObjectName(QStringLiteral("LkPrzLE2_8"));
        LkPrzLE2_8->setGeometry(QRect(580, 170, 151, 101));
        LkPrzLE2_8->setFont(font4);
        LkPrzLE2_8->setAlignment(Qt::AlignCenter);
        LkPrzLE2_9 = new QLineEdit(LkPrz2);
        LkPrzLE2_9->setObjectName(QStringLiteral("LkPrzLE2_9"));
        LkPrzLE2_9->setGeometry(QRect(760, 170, 151, 101));
        LkPrzLE2_9->setFont(font4);
        LkPrzLE2_9->setAlignment(Qt::AlignCenter);
        LkPrzLE2_0 = new QLineEdit(LkPrz2);
        LkPrzLE2_0->setObjectName(QStringLiteral("LkPrzLE2_0"));
        LkPrzLE2_0->setGeometry(QRect(40, 30, 151, 101));
        LkPrzLE2_0->setFont(font4);
        LkPrzLE2_0->setAlignment(Qt::AlignCenter);
        LkPrzLE2_1 = new QLineEdit(LkPrz2);
        LkPrzLE2_1->setObjectName(QStringLiteral("LkPrzLE2_1"));
        LkPrzLE2_1->setGeometry(QRect(220, 30, 151, 101));
        LkPrzLE2_1->setFont(font4);
        LkPrzLE2_1->setAlignment(Qt::AlignCenter);
        LkPrzLE2_2 = new QLineEdit(LkPrz2);
        LkPrzLE2_2->setObjectName(QStringLiteral("LkPrzLE2_2"));
        LkPrzLE2_2->setGeometry(QRect(400, 30, 151, 101));
        LkPrzLE2_2->setFont(font4);
        LkPrzLE2_2->setAlignment(Qt::AlignCenter);
        LkPrzLE2_3 = new QLineEdit(LkPrz2);
        LkPrzLE2_3->setObjectName(QStringLiteral("LkPrzLE2_3"));
        LkPrzLE2_3->setGeometry(QRect(580, 30, 151, 101));
        LkPrzLE2_3->setFont(font4);
        LkPrzLE2_3->setAlignment(Qt::AlignCenter);
        LkPrzLE2_4 = new QLineEdit(LkPrz2);
        LkPrzLE2_4->setObjectName(QStringLiteral("LkPrzLE2_4"));
        LkPrzLE2_4->setGeometry(QRect(760, 30, 151, 101));
        LkPrzLE2_4->setFont(font4);
        LkPrzLE2_4->setAlignment(Qt::AlignCenter);
        m_pStackWidget->addWidget(LkPrz2);
        LkPrz3 = new QWidget();
        LkPrz3->setObjectName(QStringLiteral("LkPrz3"));
        LkPrzLE3_19 = new QLineEdit(LkPrz3);
        LkPrzLE3_19->setObjectName(QStringLiteral("LkPrzLE3_19"));
        LkPrzLE3_19->setGeometry(QRect(760, 450, 151, 101));
        LkPrzLE3_19->setFont(font4);
        LkPrzLE3_19->setAlignment(Qt::AlignCenter);
        LkPrzLE3_18 = new QLineEdit(LkPrz3);
        LkPrzLE3_18->setObjectName(QStringLiteral("LkPrzLE3_18"));
        LkPrzLE3_18->setGeometry(QRect(580, 450, 151, 101));
        LkPrzLE3_18->setFont(font4);
        LkPrzLE3_18->setAlignment(Qt::AlignCenter);
        LkPrzLE3_17 = new QLineEdit(LkPrz3);
        LkPrzLE3_17->setObjectName(QStringLiteral("LkPrzLE3_17"));
        LkPrzLE3_17->setGeometry(QRect(400, 450, 151, 101));
        LkPrzLE3_17->setFont(font4);
        LkPrzLE3_17->setAlignment(Qt::AlignCenter);
        LkPrzLE3_16 = new QLineEdit(LkPrz3);
        LkPrzLE3_16->setObjectName(QStringLiteral("LkPrzLE3_16"));
        LkPrzLE3_16->setGeometry(QRect(220, 450, 151, 101));
        LkPrzLE3_16->setFont(font4);
        LkPrzLE3_16->setAlignment(Qt::AlignCenter);
        LkPrzLE3_15 = new QLineEdit(LkPrz3);
        LkPrzLE3_15->setObjectName(QStringLiteral("LkPrzLE3_15"));
        LkPrzLE3_15->setGeometry(QRect(40, 450, 151, 101));
        LkPrzLE3_15->setFont(font4);
        LkPrzLE3_15->setAlignment(Qt::AlignCenter);
        LkPrzLE3_14 = new QLineEdit(LkPrz3);
        LkPrzLE3_14->setObjectName(QStringLiteral("LkPrzLE3_14"));
        LkPrzLE3_14->setGeometry(QRect(760, 310, 151, 101));
        LkPrzLE3_14->setFont(font4);
        LkPrzLE3_14->setAlignment(Qt::AlignCenter);
        LkPrzLE3_13 = new QLineEdit(LkPrz3);
        LkPrzLE3_13->setObjectName(QStringLiteral("LkPrzLE3_13"));
        LkPrzLE3_13->setGeometry(QRect(580, 310, 151, 101));
        LkPrzLE3_13->setFont(font4);
        LkPrzLE3_13->setAlignment(Qt::AlignCenter);
        LkPrzLE3_12 = new QLineEdit(LkPrz3);
        LkPrzLE3_12->setObjectName(QStringLiteral("LkPrzLE3_12"));
        LkPrzLE3_12->setGeometry(QRect(400, 310, 151, 101));
        LkPrzLE3_12->setFont(font4);
        LkPrzLE3_12->setAlignment(Qt::AlignCenter);
        LkPrzLE3_11 = new QLineEdit(LkPrz3);
        LkPrzLE3_11->setObjectName(QStringLiteral("LkPrzLE3_11"));
        LkPrzLE3_11->setGeometry(QRect(220, 310, 151, 101));
        LkPrzLE3_11->setFont(font4);
        LkPrzLE3_11->setAlignment(Qt::AlignCenter);
        LkPrzLE3_10 = new QLineEdit(LkPrz3);
        LkPrzLE3_10->setObjectName(QStringLiteral("LkPrzLE3_10"));
        LkPrzLE3_10->setGeometry(QRect(40, 310, 151, 101));
        LkPrzLE3_10->setFont(font4);
        LkPrzLE3_10->setAlignment(Qt::AlignCenter);
        LkPrzLE3_5 = new QLineEdit(LkPrz3);
        LkPrzLE3_5->setObjectName(QStringLiteral("LkPrzLE3_5"));
        LkPrzLE3_5->setGeometry(QRect(40, 170, 151, 101));
        LkPrzLE3_5->setFont(font4);
        LkPrzLE3_5->setAlignment(Qt::AlignCenter);
        LkPrzLE3_6 = new QLineEdit(LkPrz3);
        LkPrzLE3_6->setObjectName(QStringLiteral("LkPrzLE3_6"));
        LkPrzLE3_6->setGeometry(QRect(220, 170, 151, 101));
        LkPrzLE3_6->setFont(font4);
        LkPrzLE3_6->setAlignment(Qt::AlignCenter);
        LkPrzLE3_7 = new QLineEdit(LkPrz3);
        LkPrzLE3_7->setObjectName(QStringLiteral("LkPrzLE3_7"));
        LkPrzLE3_7->setGeometry(QRect(400, 170, 151, 101));
        LkPrzLE3_7->setFont(font4);
        LkPrzLE3_7->setAlignment(Qt::AlignCenter);
        LkPrzLE3_8 = new QLineEdit(LkPrz3);
        LkPrzLE3_8->setObjectName(QStringLiteral("LkPrzLE3_8"));
        LkPrzLE3_8->setGeometry(QRect(580, 170, 151, 101));
        LkPrzLE3_8->setFont(font4);
        LkPrzLE3_8->setAlignment(Qt::AlignCenter);
        LkPrzLE3_9 = new QLineEdit(LkPrz3);
        LkPrzLE3_9->setObjectName(QStringLiteral("LkPrzLE3_9"));
        LkPrzLE3_9->setGeometry(QRect(760, 170, 151, 101));
        LkPrzLE3_9->setFont(font4);
        LkPrzLE3_9->setAlignment(Qt::AlignCenter);
        LkPrzLE3_0 = new QLineEdit(LkPrz3);
        LkPrzLE3_0->setObjectName(QStringLiteral("LkPrzLE3_0"));
        LkPrzLE3_0->setGeometry(QRect(40, 30, 151, 101));
        LkPrzLE3_0->setFont(font4);
        LkPrzLE3_0->setAlignment(Qt::AlignCenter);
        LkPrzLE3_1 = new QLineEdit(LkPrz3);
        LkPrzLE3_1->setObjectName(QStringLiteral("LkPrzLE3_1"));
        LkPrzLE3_1->setGeometry(QRect(220, 30, 151, 101));
        LkPrzLE3_1->setFont(font4);
        LkPrzLE3_1->setAlignment(Qt::AlignCenter);
        LkPrzLE3_2 = new QLineEdit(LkPrz3);
        LkPrzLE3_2->setObjectName(QStringLiteral("LkPrzLE3_2"));
        LkPrzLE3_2->setGeometry(QRect(400, 30, 151, 101));
        LkPrzLE3_2->setFont(font4);
        LkPrzLE3_2->setAlignment(Qt::AlignCenter);
        LkPrzLE3_3 = new QLineEdit(LkPrz3);
        LkPrzLE3_3->setObjectName(QStringLiteral("LkPrzLE3_3"));
        LkPrzLE3_3->setGeometry(QRect(580, 30, 151, 101));
        LkPrzLE3_3->setFont(font4);
        LkPrzLE3_3->setAlignment(Qt::AlignCenter);
        LkPrzLE3_4 = new QLineEdit(LkPrz3);
        LkPrzLE3_4->setObjectName(QStringLiteral("LkPrzLE3_4"));
        LkPrzLE3_4->setGeometry(QRect(760, 30, 151, 101));
        LkPrzLE3_4->setFont(font4);
        LkPrzLE3_4->setAlignment(Qt::AlignCenter);
        m_pStackWidget->addWidget(LkPrz3);
        LuckyPrize = new QPushButton(centralWidget);
        LuckyPrize->setObjectName(QStringLiteral("LuckyPrize"));
        LuckyPrize->setGeometry(QRect(10, 300, 221, 51));
        LuckyPrize->setFont(font);
        Start = new QPushButton(centralWidget);
        Start->setObjectName(QStringLiteral("Start"));
        Start->setGeometry(QRect(10, 510, 221, 61));
        Start->setFont(font);
        Pause = new QPushButton(centralWidget);
        Pause->setObjectName(QStringLiteral("Pause"));
        Pause->setGeometry(QRect(10, 590, 221, 61));
        Pause->setFont(font);
        ThirdPrize_2 = new QPushButton(centralWidget);
        ThirdPrize_2->setObjectName(QStringLiteral("ThirdPrize_2"));
        ThirdPrize_2->setGeometry(QRect(10, 230, 221, 51));
        ThirdPrize_2->setFont(font);
        LuckyPrize_2 = new QPushButton(centralWidget);
        LuckyPrize_2->setObjectName(QStringLiteral("LuckyPrize_2"));
        LuckyPrize_2->setGeometry(QRect(10, 370, 221, 51));
        LuckyPrize_2->setFont(font);
        LuckyPrize_3 = new QPushButton(centralWidget);
        LuckyPrize_3->setObjectName(QStringLiteral("LuckyPrize_3"));
        LuckyPrize_3->setGeometry(QRect(10, 440, 221, 51));
        LuckyPrize_3->setFont(font);
        LotteryPageClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(LotteryPageClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1181, 26));
        LotteryPageClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(LotteryPageClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        LotteryPageClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(LotteryPageClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        LotteryPageClass->setStatusBar(statusBar);

        retranslateUi(LotteryPageClass);

        m_pStackWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(LotteryPageClass);
    } // setupUi

    void retranslateUi(QMainWindow *LotteryPageClass)
    {
        LotteryPageClass->setWindowTitle(QApplication::translate("LotteryPageClass", "LotteryPage", nullptr));
        ThirdPrize->setText(QApplication::translate("LotteryPageClass", "ThirdPrize", nullptr));
        SecondPrize->setText(QApplication::translate("LotteryPageClass", "SecondPrize", nullptr));
        FirstPrize->setText(QApplication::translate("LotteryPageClass", "FirstPrize", nullptr));
        SecondPrizeBtn_0->setText(QApplication::translate("LotteryPageClass", "Restart", nullptr));
        SecondPrizeBtn_1->setText(QApplication::translate("LotteryPageClass", "Restart", nullptr));
        SecondPrizeBtn_2->setText(QApplication::translate("LotteryPageClass", "Restart", nullptr));
        SecondPrizeBtn_3->setText(QApplication::translate("LotteryPageClass", "Restart", nullptr));
        SecondPrizeBtn_4->setText(QApplication::translate("LotteryPageClass", "Restart", nullptr));
        SecondPrizeBtn_5->setText(QApplication::translate("LotteryPageClass", "Restart", nullptr));
        LuckyPrize->setText(QApplication::translate("LotteryPageClass", "LuckyPrize", nullptr));
        Start->setText(QApplication::translate("LotteryPageClass", "Start", nullptr));
        Pause->setText(QApplication::translate("LotteryPageClass", "Pause", nullptr));
        ThirdPrize_2->setText(QApplication::translate("LotteryPageClass", "ThirdPrize2", nullptr));
        LuckyPrize_2->setText(QApplication::translate("LotteryPageClass", "LuckyPrize2", nullptr));
        LuckyPrize_3->setText(QApplication::translate("LotteryPageClass", "LuckyPrize3", nullptr));
    } // retranslateUi

};

namespace Ui {
    class LotteryPageClass: public Ui_LotteryPageClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LOTTERYPAGE_H
